"""
prepare_report_context.py
──────────────────────────
Step 2 — reads the prefetched data and writes REPORT_CONTEXT.md.

USAGE
─────
    python prepare_report_context.py --site "Flowserve US Raleigh NC (US)" --month "May 2026"

OUTPUT
──────
    data_store/flowserve_us_raleigh_nc_us_may_2026/REPORT_CONTEXT.md

Open that file in VS Code, open Copilot Chat (Ctrl+Shift+I),
paste the task from Section 8 at the bottom.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT       = Path(__file__).parent
DATA_STORE = ROOT / "data_store"


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--site",  required=True)
    p.add_argument("--month", required=True)
    return p.parse_args()


def slugify(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")


def main():
    args = parse_args()
    site_name       = args.site
    reporting_month = args.month

    cache_dir = DATA_STORE / slugify(f"{site_name}_{reporting_month}")
    if not (cache_dir / "manifest.json").exists():
        print(f"[ERROR] No prefetch data found at: {cache_dir}")
        print(f"  Run first:  python prefetch_site.py --site \"{site_name}\" --month \"{reporting_month}\"")
        sys.exit(1)

    print(f"Building REPORT_CONTEXT.md for {site_name} | {reporting_month} ...")

    # Load all files
    controllers   = _load_json(cache_dir / "controllers.json",   [])
    service_notes = _load_json(cache_dir / "service_notes.json", [])
    ade_data      = _load_json(cache_dir / "ade_data.json",      [])
    scc_data      = _load_json(cache_dir / "scc.json",           [])
    manifest      = _load_json(cache_dir / "manifest.json",      {})

    telem_summaries = {}
    for f in sorted((cache_dir / "telemetry").glob("*_summary.json")):
        serial = f.stem.replace("_summary", "")
        telem_summaries[serial] = json.loads(f.read_text())

    lines = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        f"# REPORT CONTEXT — {site_name}",
        f"## Reporting Month: {reporting_month}",
        f"",
        f"> Auto-generated by prepare_report_context.py — open in VS Code with Copilot Chat.",
        f"> Copilot task prompt is at the bottom (Section 8).",
        f"",
        f"**Prefetch date:** {manifest.get('fetched_at', 'unknown')}",
        f"**Data period:** {manifest.get('start_date')} → {manifest.get('end_date')}",
        f"**Telemetry days:** {manifest.get('telemetry_days', 90)}",
        "", "---", "",
    ]

    # ── Section 1: Controllers ────────────────────────────────────────────────
    lines += [
        "## 1. Controllers at this site", "",
        "| Serial Number | System Name | Plant System |",
        "|---|---|---|",
    ]
    for c in controllers:
        lines.append(f"| {c.get('SerialNumber')} | {c.get('SystemName','')} | {c.get('PlantSystemName','')} |")
    lines += ["", "---", ""]

    # ── Section 2: SCC — Site-specific setpoints & alarm limits ──────────────
    lines += [
        "## 2. SCC — Site-Specific Setpoints & Alarm Limits",
        "",
        "> **These are the actual programmed limits for this site from Cosmos DB.**",
        "> Use these instead of the generic Buckman standard limits when available.",
        "> SP = Control Setpoint | DB = Dead Band | HH = High-High alarm | LL = Low-Low alarm",
        "> H = High alarm | L = Low alarm",
        "",
    ]

    if scc_data:
        # Group by controller
        by_ctrl: dict = {}
        for row in scc_data:
            ctrl = row.get("ControllerId", "unknown")
            by_ctrl.setdefault(ctrl, []).append(row)

        for ctrl_id, rows in by_ctrl.items():
            lines += [f"### Controller: {ctrl_id}", ""]

            # Alarm limits table (sensors that have HH/LL/H/L but no relay)
            alarm_rows = [r for r in rows if r.get("HH") or r.get("LL") or r.get("H") or r.get("L")]
            if alarm_rows:
                lines += [
                    "**Alarm Limits (what triggers an alarm):**",
                    "",
                    "| Sensor | HH | H | L | LL |",
                    "|---|---|---|---|---|",
                ]
                seen = set()
                for r in alarm_rows:
                    sensor = r.get("Sensor Name") or r.get("Input Sensor", "")
                    if sensor in seen:
                        continue
                    seen.add(sensor)
                    lines.append(
                        f"| {sensor} "
                        f"| {r.get('HH','–')} "
                        f"| {r.get('H','–')} "
                        f"| {r.get('L','–')} "
                        f"| {r.get('LL','–')} |"
                    )
                lines += [""]

            # Control setpoints table (sensors with SP and a relay)
            ctrl_rows = [r for r in rows if r.get("SP") not in (None, "", "NULL") and r.get("Exact Relay")]
            if ctrl_rows:
                lines += [
                    "**Control Setpoints (what the controller targets):**",
                    "",
                    "| Sensor | Relay | Product | SP | DB | Control Type | Timeout (min) |",
                    "|---|---|---|---|---|---|---|",
                ]
                for r in ctrl_rows:
                    sensor = r.get("Sensor Name") or r.get("Input Sensor", "")
                    lines.append(
                        f"| {sensor} "
                        f"| {r.get('Exact Relay','–')} "
                        f"| {r.get('Product Name','–')} "
                        f"| {r.get('SP','–')} "
                        f"| {r.get('DB','–')} "
                        f"| {r.get('Control Type','–')} "
                        f"| {r.get('Relay Timeout (min)','–')} |"
                    )
                lines += [""]

            # Fluorometer calibration
            fluoro_rows = [r for r in rows if r.get("CustomRatio") not in (None, "")]
            if fluoro_rows:
                lines += ["**Fluorometer Calibration:**", ""]
                for r in fluoro_rows:
                    sensor = r.get("Sensor Name") or r.get("Input Sensor", "")
                    lines.append(
                        f"- {sensor}: CustomRatio = {r.get('CustomRatio')}  |  "
                        f"BackgroundValue = {r.get('BackgroundValue','?')}"
                    )
                lines += [""]
    else:
        lines += [
            "> ⚠ No SCC data available. This may mean:",
            "> - COSMOS_URL / COSMOS_KEY not set in .env",
            "> - The controller was not found in Cosmos",
            "> - Run prefetch again with valid Cosmos credentials",
            "",
            "> Falling back to standard Buckman limits (Section 6).",
            "",
        ]

    lines += ["---", ""]

    # ── Section 3: Telemetry KPIs ─────────────────────────────────────────────
    lines += [
        "## 3. Telemetry KPIs",
        "",
        "> Sensor averages, min, max, last reading from 90-day telemetry.",
        "> Compare these against the SCC limits in Section 2 to identify deviations.",
        "",
    ]
    for serial, summary in telem_summaries.items():
        lines += [f"### Controller: {serial}", ""]
        tr = summary.get("time_range", {})
        lines += [
            f"- **Data period:** {tr.get('from','?')} → {tr.get('to','?')}",
            f"- **Total rows:** {summary.get('total_rows',0):,}",
            "",
            "| Sensor | Mean | Min | Max | Last |",
            "|---|---|---|---|---|",
        ]
        for sensor, stats in summary.get("sensors", {}).items():
            lines.append(
                f"| {sensor} | {stats.get('mean')} | {stats.get('min')} "
                f"| {stats.get('max')} | {stats.get('last')} |"
            )
        lines += ["", "**Recent 20 readings per sensor (for trend analysis):**", ""]
        for sensor, stats in summary.get("sensors", {}).items():
            lines.append(f"- `{sensor}`: {stats.get('recent_20', [])}")
        lines += [""]

    lines += ["---", ""]

    # ── Section 4: ADE / MDE data ─────────────────────────────────────────────
    lines += [
        "## 4. ADE / MDE Field Test Data",
        "",
        "> Hand-measured values from site visits. FRC must come from here — not from ORP.",
        "",
        "| Date | Context Point | Parameter | Value | Engineer |",
        "|---|---|---|---|---|",
    ]
    for row in ade_data:
        dt = str(row.get("CreatedDateTime", ""))[:10]
        lines.append(
            f"| {dt} | {row.get('ContextVertexName','')} "
            f"| {row.get('Parameter','')} | {row.get('Value','')} "
            f"| {row.get('PSRFullName','')} |"
        )

    # FRC highlight
    frc_rows = [r for r in ade_data if any(
        k in str(r.get("Parameter","")).lower()
        for k in ("free residual", "frc", "halogen")
    )]
    lines += [""]
    if frc_rows:
        frc_vals = []
        for r in frc_rows:
            try:
                frc_vals.append(float(r["Value"]))
            except (TypeError, ValueError):
                pass
        frc_avg = round(sum(frc_vals) / len(frc_vals), 2) if frc_vals else None
        lines += [
            f"**⚠ FRC (Free Residual Chlorine) from ADE data:**",
            f"- Readings: {[r['Value'] for r in frc_rows]}",
            f"- Average: {frc_avg} ppm",
            f"- Use this value in Microbial Control. Do NOT infer FRC from ORP.",
            "",
        ]
    else:
        lines += [
            "**⚠ FRC: NOT FOUND in ADE data for this period.**",
            "- State in report: FRC was not available and will be checked at the upcoming service visit.",
            "",
        ]

    lines += ["---", ""]

    # ── Section 5: Service Notes ──────────────────────────────────────────────
    lines += [
        "## 5. Service Notes",
        "",
        "> Look for 'Actions Completed' or 'Notes from the field' sections.",
        "> These describe what the engineer actually did on site.",
        "",
    ]
    if not service_notes:
        lines += ["*No service notes found for this period.*", ""]
    for i, note in enumerate(service_notes, 1):
        lines += [
            f"### Note {i} — {str(note.get('CreatedDate',''))[:10]}",
            f"- **Context point:** {note.get('ContextPoint','')}",
            f"- **Status:** {note.get('Status','')}",
            f"- **Modified:** {str(note.get('ModifiedDate',''))[:10]}",
            "",
            note.get("ServiceNotePlain") or _strip_html(note.get("ServiceNote","")),
            "",
        ]

    lines += ["---", ""]

    # ── Section 6: Standard limits fallback ───────────────────────────────────
    lines += [
        "## 6. Standard Buckman Limits (fallback if SCC not available)",
        "",
        "> Use Section 2 (SCC) limits first. Only use these if Section 2 is empty.",
        "",
        "| Parameter | Lower Limit | Upper Limit | Unit |",
        "|---|---|---|---|",
        "| Mild Steel Corrosion | 0 | 3.0 | MPY |",
        "| Copper Corrosion | 0 | 0.5 | MPY |",
        "| pH | 7.5 | 9.5 | pH |",
        "| ORP | 100 | 700 | mV |",
        "| Traced Product | 60 | 130 | ppm |",
        "| Electrode Conductivity | 800 | 1500 | µS/cm |",
        "| Turbidity | 0 | 75 | NTU |",
        "| Cell Fouling | 0 | 30 | % |",
        "", "---", "",
    ]

    # ── Section 7: Training examples ──────────────────────────────────────────
    lines += [
        "## 7. Training Report Examples",
        "",
        "| File | Site | Key examples |",
        "|---|---|---|",
        "| `training_reports/Flowserve_report.pdf` | Flowserve US Raleigh NC | ORP spike inconsistency, copper corrosion deviation, 98% GoC |",
        "| `training_reports/st_joseph_report.pdf` | St. Joseph's Hospital Savannah GA | 100% GoC, clean delta ORP, inventory section |",
        "| `training_reports/Synthomer_Cooling_Tower_Performance_Report_-_May_26.pdf` | Synthomer Chester SC | COC deviation, water loss, Delta ORP upgrade |",
        "", "---", "",
    ]

    # ── Section 8: Copilot Task ───────────────────────────────────────────────
    slug_site  = slugify(site_name)
    slug_month = slugify(reporting_month)
    cache_slug = slugify(site_name + "_" + reporting_month)
    lines += [
        "## 8. Copilot Task — Paste this into Copilot Chat",
        "",
        "> Copy everything between the triple backticks and paste into GitHub Copilot Chat.",
        "> Make sure REPORT_CONTEXT.md AND the output .md file are both open in the editor.",
        "",
        "```",
        f"You are a monthly cooling water performance report agent for Buckman Digital Water.",
        f"Read ALL sections of data_store/{cache_slug}/REPORT_CONTEXT.md before writing anything.",
        f"Generate the complete monthly report for {site_name}, {reporting_month}.",
        f"",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"SELF-CHECK — answer these before writing a single word:",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"1.  SCC control range for Traced Product = SP minus DB to SP plus DB. What is it?",
        f"2.  Count how many recent_20 Traced Product readings fall inside that range. What %?",
        f"3.  Is that % above 75% (Good), 25-75% (Stable), or below 25% (Action Required)?",
        f"4.  SCC control range for Conductivity. What is it?",
        f"5.  How many recent_20 Conductivity readings are inside that range?",
        f"6.  Did Conductivity move with Traced Product or stay stable?",
        f"7.  Root cause: if Conductivity was stable = product feed issue. If both dropped = water loss.",
        f"8.  Is FRC in Section 4 ADE data? Yes/No.",
        f"9.  What does the biocide relay recent_20 show — was it firing?",
        f"10. Are there Actions Completed in Section 5 service notes?",
        f"11. For each sensor in Section 3, split recent_20 into 4 groups of 5 — these are the monthly trend.",
        f"",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"SECTION RULES — follow every rule exactly:",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"",
        f"CORROSION CONTROL:",
        f"  Use this exact wording:",
        f"  'The average mild steel corrosion rate was X MPY against the target of within 3.0 MPY,",
        f"  and the average copper corrosion rate was X MPY against the target of within 0.5 MPY.'",
        f"  Follow with a one-month trend chart (ASCII line chart or bar chart) using recent_20",
        f"  corrosion data split into 4 weekly groups. Add comment below chart.",
        f"",
        f"SCALE CONTROL — STRICT RULES:",
        f"  Write ONLY about Traced Product (Fluorometer Ch1) in this section.",
        f"  DO NOT mention conductivity, pH, turbidity, or any other parameter here.",
        f"  Status MUST reflect the % in range from recent_20 — NOT the 90-day mean.",
        f"  If % in range < 25% → status is ACTION REQUIRED — not Good, not Stable.",
        f"  If % in range = 0% → write: '[product] was never within the SCC programmed control range'",
        f"  Root cause (use conductivity from your self-check, but state it as root cause explanation):",
        f"    conductivity stable + traced product above range = product feed issue (pump/calibration)",
        f"    both dropped together = water loss or dilution",
        f"  If Traced Product is LOW (below SCC lower limit):",
        f"    Observation: state the product level is below the SCC lower control limit.",
        f"    Recommendation: check dosing pump operation, verify product inventory,",
        f"    inspect feed line for blockage or air lock, verify fluorometer calibration.",
        f"  If Traced Product is HIGH (above SCC upper limit):",
        f"    Observation: state the product level is above the SCC upper control limit.",
        f"    Recommendation: check dosing pump rate, verify fluorometer calibration,",
        f"    review dosing schedule, reduce feed rate if pump is operating correctly.",
        f"  Follow the narrative with a one-month trend chart of Traced Product only.",
        f"  Chart must be an ASCII line chart showing trend across the month.",
        f"  Add comment below chart.",
        f"",
        f"MICROBIAL CONTROL — STRICT RULES:",
        f"  Write ONLY about FRC and ORP spike response in this section.",
        f"  DO NOT mention pH, turbidity, cell fouling, or any other parameter here.",
        f"  Those parameters belong in the Performance Summary table only.",
        f"  FRC comment: use ONLY Section 4 ADE data. Never infer FRC from ORP.",
        f"  If FRC not in Section 4 write exactly:",
        f"    'FRC data was not available in the MDE data for this reporting period",
        f"    and will be checked during the upcoming service visit.'",
        f"  ORP SPIKE COMMENT IS MANDATORY — always include:",
        f"    'ORP spike response after timer-controlled biocide feed [was consistent /",
        f"    was not consistent], indicating [the system responded to treatment /",
        f"    microbial control should continue to be reviewed during the upcoming service visit].'",
        f"  NEVER write absolute ORP values anywhere. Spike language only.",
        f"  Follow with a one-month ORP trend chart showing spike patterns across the month.",
        f"  Chart must be an ASCII line chart. Add comment below chart.",
        f"",
        f"WATER EFFICIENCY:",
        f"  Discuss conductivity and COC here — not in Scale Control.",
        f"  Follow with a one-month Conductivity trend chart using recent_20 data.",
        f"  Chart must be an ASCII line chart showing setpoint line vs actual readings.",
        f"  Add comment below chart.",
        f"",
        f"PRODUCT EFFICIENCY:",
        f"  Discuss product consumption and dosing efficiency here.",
        f"  If actual consumption data is available, compare to expected.",
        f"  If not available, state it will be reviewed at next service visit.",
        f"",
        f"PROACTIVE SYSTEM SUPPORT:",
        f"  Always use this exact title. Never 'Alarms'.",
        f"  List alarms with count, root cause, action taken, current status.",
        f"",
        f"STATUS LABELS:",
        f"  Every Health Check subsection MUST start with exactly one of:",
        f"  **Status: Good** or **Status: Stable** or **Status: Action Required**",
        f"  Good           = > 75% of recent_20 readings within SCC control range",
        f"  Stable         = 25-75% of recent_20 readings within SCC control range",
        f"  Action Required = < 25% of recent_20 readings within SCC control range",
        f"",
        f"SCC DATA RULES:",
        f"  Use Section 2 SCC limits everywhere. Only use Section 6 if Section 2 is empty.",
        f"  Use the Product Name from SCC Section 2 — never write 'inhibitor' or 'biocide'.",
        f"  Control range = SP minus DB  to  SP plus DB.",
        f"",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"CHARTS — ALL charts must be ASCII line charts (not tables):",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"Use this ASCII line chart format for every chart:",
        f"",
        f"  [Parameter Name] — [Month Year]",
        f"  SCC range: [LL] – [UL] [unit]",
        f"",
        f"  [UL] |--------------------------------------------  ← upper limit line",
        f"       |        *    *                                ",
        f"       |   *         *    *    *    *    *    *    *  ← data points",
        f"       |                                              ",
        f"  [LL] |--------------------------------------------  ← lower limit line",
        f"       W1          W2          W3          W4",
        f"       (readings 1-5) (6-10)  (11-15)  (16-20)",
        f"",
        f"  Use * for data points. Show UL and LL as dashed lines (----).",
        f"  Label the x-axis as W1 W2 W3 W4 (weekly groups from recent_20).",
        f"  Scale the y-axis to fit the data range.",
        f"  For ORP chart: show spike peaks — use ^ for spike points above baseline.",
        f"",
        f"Include charts for these parameters in this order:",
        f"  1. Traced Product trend chart (in Scale Control section)",
        f"  2. ORP trend chart showing spike pattern (in Microbial Control section)",
        f"  3. Conductivity trend chart vs SCC setpoint (in Water Efficiency section)",
        f"  4. Corrosion trend chart MS and Cu (in Performance Summary or after it)",
        f"  5. Any other parameter that was outside SCC range during the month",
        f"",
        f"Each chart must be immediately followed by a Comment paragraph:",
        f"  Comment must explain: what the trend shows, root cause if deviating,",
        f"  what action was taken or is recommended.",
        f"",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"REPORT STRUCTURE:",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"Page 1:  Title page — site name, month, prepared date, report status",
        f"Pages 2-3: Executive Summary — narrative prose + inline charts:",
        f"           Corrosion Control + corrosion trend chart + comment",
        f"           Scale Control (Traced Product ONLY) + trend chart + comment",
        f"           Microbial Control (FRC + ORP ONLY) + ORP trend chart + comment",
        f"           Water Efficiency + conductivity trend chart + comment",
        f"           Product Efficiency",
        f"           Proactive System Support",
        f"Page 4:  Performance Summary table — ALL parameters, SCC limits, % in range",
        f"Pages 5+: Additional charts for any parameters outside SCC range + comments",
        f"Last:    Final Release Approval checklist",
        f"",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"STEPS:",
        f"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        f"STEP 1 — Write the full report into:",
        f"  output/{slug_site}_{slug_month}_report.md",
        f"",
        f"STEP 2 — Write a Node.js script at scripts/build_report.js using the docx npm",
        f"  package. Use Buckman green #00857C for headings and table headers.",
        f"  Status colours: Good=green #00857C, Stable=amber #B8860B, Action Required=red #C00000.",
        f"  Render every ASCII chart as a monospace code block in the Word doc",
        f"  using a Courier New paragraph with light grey background shading.",
        f"  Header every page: site name | report title.",
        f"  Footer every page: Buckman Digital Water | Confidential   Page X.",
        f"  Use SimpleField('PAGE') for page numbers — not PageNumber constructor.",
        f"  Set both columnWidths on Table AND width on every TableCell.",
        f"  Use ShadingType.CLEAR not SOLID.",
        f"  Never use \n inside TextRun — use separate Paragraphs.",
        f"  Then run: node scripts/build_report.js",
        f"  Save to:   output/{slug_site}_{slug_month}_report.docx",
        "```",
        "",
    ]

    out_path = cache_dir / "REPORT_CONTEXT.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"✅  REPORT_CONTEXT.md written → {out_path}")
    print(f"")
    _create_output_stubs(ROOT, site_name, reporting_month)
    print(f"")
    print(f"Next steps:")
    print(f"  1. Open VS Code:         code .")
    print(f"  2. Open BOTH files in the editor:")
    print(f"       {out_path.relative_to(ROOT)}")
    print(f"       output/{slugify(site_name)}_{slugify(reporting_month)}_report.md")
    print(f"  3. Open Copilot Chat:    Ctrl+Shift+I")
    print(f"  4. Paste the task from Section 8 at the bottom of REPORT_CONTEXT.md")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_json(path: Path, default):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return default


def _strip_html(html: str) -> str:
    if not html:
        return ""
    text = re.sub(r"<[^>]+>", " ", html)
    for ent, rep in [("&nbsp;", " "), ("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">")]:
        text = text.replace(ent, rep)
    return re.sub(r"\s{2,}", " ", text).strip()



def _create_output_stubs(root, site_name, reporting_month):
    """
    Create the empty output files and scripts folder so Copilot Agent
    can write to them directly without needing to create new files.
    """
    slug = slugify(f"{site_name}_{reporting_month}")

    # output folder + empty .md and .docx stubs
    out_dir = root / "output"
    out_dir.mkdir(exist_ok=True)

    md_file = out_dir / f"{slug}_report.md"
    if not md_file.exists():
        md_file.write_text(
            f"# {site_name}\n## {reporting_month} — Pending Copilot generation\n",
            encoding="utf-8"
        )

    docx_stub = out_dir / f"{slug}_report.docx"
    if not docx_stub.exists():
        docx_stub.write_bytes(b"")   # empty placeholder

    # scripts folder for the Node.js build script Copilot will write
    scripts_dir = root / "scripts"
    scripts_dir.mkdir(exist_ok=True)
    readme = scripts_dir / "README.md"
    if not readme.exists():
        readme.write_text(
            "# Scripts\nCopilot writes `build_report.js` here when generating the Word document.\n",
            encoding="utf-8"
        )

    print(f"✅  Output stubs created:")
    print(f"    {md_file.relative_to(root)}  ← open this in VS Code before running Copilot")
    print(f"    {docx_stub.relative_to(root)}")
    print(f"    {scripts_dir.relative_to(root)}/  ← Copilot will write build_report.js here")


if __name__ == "__main__":
    main()